/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Main extends javax.swing.JFrame {

    /**
     * Creates new form Program_1
     */
    
    public Main() {
        initComponents();
        this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // This class defines the gradient panel
class jPanelGradient extends JPanel {
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Always call super.paintComponent(g)
        
        Graphics2D g2d = (Graphics2D) g;
        int width = getWidth();
        int height = getHeight();
        
        // Define lighter pastel colors by mixing original colors with white
        Color color1 = new Color(255, 210, 220); // Lighter Pink (mix of pink and white)
        Color color2 = new Color(230, 210, 230); // Lighter Purple (mix of purple and white)
        Color color3 = new Color(200, 230, 255); // Lighter Blue (mix of blue and white)
        
        // Create a gradient paint with three lighter colors
        GradientPaint gradient = new GradientPaint(0, 0, color1, width, height, color3);
        
        // Set the graphics object to use the gradient
        g2d.setPaint(gradient);
        
        // Fill the entire panel with the gradient
        g2d.fillRect(0, 0, width, height);
    }
}

// This class defines the transparent panel
class jPanelTransparent extends JPanel {
    public jPanelTransparent() {
        // Set panel to be transparent for background
        setOpaque(false);
    }

    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Always call super.paintComponent(g)
        
        Graphics2D g2d = (Graphics2D) g;
        int width = getWidth();
        int height = getHeight();
        
        // Set the color to white with some transparency (alpha = 128 for 50% transparency)
        Color semiTransparentWhite = new Color(255, 255, 255, 128); // White with 50% opacity

        // Fill the entire panel with a semi-transparent white background
        g2d.setColor(semiTransparentWhite);
        g2d.fillRect(0, 0, width, height); // Fill the entire panel area
    }
}

/*private void resetButtonColors() {
    // Reset all buttons to their default color
    Program_1BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_2BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_3BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_4BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_5BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_6BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_7BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_8BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_9BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_10BTN.setBackground(new java.awt.Color(250, 250, 245));
    // Add more buttons if necessary
}*/

   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        IconMinMax = new javax.swing.JPanel();
        BTNMax = new javax.swing.JPanel();
        MaxIcon = new javax.swing.JLabel();
        BTNClose = new javax.swing.JPanel();
        ExitIcon = new javax.swing.JLabel();
        BTNMin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MainBoard = new jPanelGradient();
        jPanel2 = new jPanelTransparent();
        Dashboard_BTN = new javax.swing.JButton();
        App_BTN = new javax.swing.JButton();
        Dev_BTN = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(800, 35));
        Header.setLayout(new java.awt.BorderLayout());

        IconMinMax.setBackground(new java.awt.Color(0, 0, 51));
        IconMinMax.setPreferredSize(new java.awt.Dimension(150, 50));
        IconMinMax.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNMax.setBackground(new java.awt.Color(255, 255, 255));

        MaxIcon.setBackground(new java.awt.Color(255, 255, 255));
        MaxIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/2.png"))); // NOI18N
        MaxIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaxIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaxIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaxIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BTNMaxLayout = new javax.swing.GroupLayout(BTNMax);
        BTNMax.setLayout(BTNMaxLayout);
        BTNMaxLayout.setHorizontalGroup(
            BTNMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MaxIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BTNMaxLayout.setVerticalGroup(
            BTNMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNMaxLayout.createSequentialGroup()
                .addComponent(MaxIcon)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        IconMinMax.add(BTNMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, -1));

        BTNClose.setBackground(new java.awt.Color(255, 255, 255));

        ExitIcon.setBackground(new java.awt.Color(255, 255, 255));
        ExitIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.png"))); // NOI18N
        ExitIcon.setToolTipText("");
        ExitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BTNCloseLayout = new javax.swing.GroupLayout(BTNClose);
        BTNClose.setLayout(BTNCloseLayout);
        BTNCloseLayout.setHorizontalGroup(
            BTNCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitIcon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BTNCloseLayout.setVerticalGroup(
            BTNCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNCloseLayout.createSequentialGroup()
                .addComponent(ExitIcon)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        IconMinMax.add(BTNClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, -1));

        BTNMin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BTNMinLayout = new javax.swing.GroupLayout(BTNMin);
        BTNMin.setLayout(BTNMinLayout);
        BTNMinLayout.setHorizontalGroup(
            BTNMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        BTNMinLayout.setVerticalGroup(
            BTNMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        IconMinMax.add(BTNMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        Header.add(IconMinMax, java.awt.BorderLayout.LINE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        Header.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jLabel1.setBackground(new java.awt.Color(118, 16, 198));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        MainBoard.setBackground(new java.awt.Color(255, 246, 255));

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));

        Dashboard_BTN.setBackground(new java.awt.Color(118, 16, 198));
        Dashboard_BTN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Dashboard_BTN.setForeground(new java.awt.Color(255, 255, 255));
        Dashboard_BTN.setText("Proceed to Dashboard");
        Dashboard_BTN.setToolTipText("");
        Dashboard_BTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Dashboard_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Dashboard_BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Dashboard_BTNMouseExited(evt);
            }
        });
        Dashboard_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dashboard_BTNActionPerformed(evt);
            }
        });

        App_BTN.setBackground(new java.awt.Color(250, 250, 245));
        App_BTN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        App_BTN.setText("About the App");
        App_BTN.setToolTipText("");
        App_BTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        App_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                App_BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                App_BTNMouseExited(evt);
            }
        });
        App_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                App_BTNActionPerformed(evt);
            }
        });

        Dev_BTN.setBackground(new java.awt.Color(250, 250, 245));
        Dev_BTN.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        Dev_BTN.setText("About the Developer");
        Dev_BTN.setToolTipText("");
        Dev_BTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        Dev_BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Dev_BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Dev_BTNMouseExited(evt);
            }
        });
        Dev_BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dev_BTNActionPerformed(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/Logo_Bayan.png"))); // NOI18N
        jLabel4.setLabelFor(BTNClose);

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("Technology for Every Juan");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel23))
                    .addComponent(jLabel20))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(131, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Dev_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(App_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Dashboard_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(116, 116, 116))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel18)
                        .addGap(101, 101, 101))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(163, 163, 163))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addComponent(jLabel4)
                .addGap(31, 31, 31)
                .addComponent(jLabel18)
                .addGap(77, 77, 77)
                .addComponent(Dashboard_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(App_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(Dev_BTN, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel23)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 50)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(118, 16, 198));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("BayanApp! ");

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 50)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Welcome to");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/welcome.png"))); // NOI18N

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel19.setText("Your one-stop mini-application designed to assist, educate, and empower Filipinos through technology.");

        javax.swing.GroupLayout MainBoardLayout = new javax.swing.GroupLayout(MainBoard);
        MainBoard.setLayout(MainBoardLayout);
        MainBoardLayout.setHorizontalGroup(
            MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainBoardLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addGroup(MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBoardLayout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addGap(214, 214, 214))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBoardLayout.createSequentialGroup()
                        .addComponent(jLabel19)
                        .addGap(58, 58, 58))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBoardLayout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addGap(174, 174, 174)))
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        MainBoardLayout.setVerticalGroup(
            MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBoardLayout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addGroup(MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel19)
                .addGap(34, 34, 34)
                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(MainBoard, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1416, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void changecolor(JPanel hover, Color rand)
    {
        hover.setBackground(rand);
    }
    
    public void clickMenu(JPanel h1, int numberbool)
    {
        if (numberbool == 1)
        {
            h1.setBackground(new Color(255,255,204));
            //h2.setBackground(new Color(5,10,46));
        }
        else
        {
            h1.setBackground(new Color(200,200,200));
            //h2.setBackground(new Color(25,29,74));
        }
    }
    
    public void hideShow(JPanel menushowhide, boolean dashboard) {
        if (dashboard) {
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
        } else {
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
        }
    }


    
    private void ExitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitIconMouseClicked
        int confirm = JOptionPane.showConfirmDialog(
                this, 
                "Are you sure you want to exit BayanApp?", 
                "Exit Confirmation", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if (confirm == JOptionPane.YES_OPTION) {
                Bye byePage = new Bye();
                byePage.setVisible(true);

                this.setVisible(false);

                new javax.swing.Timer(2000, (e) -> {
                    System.exit(0);
                }).start();
            }
    }//GEN-LAST:event_ExitIconMouseClicked

    private void MaxIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxIconMouseClicked
        if(this.getExtendedState()!= Program_1.MAXIMIZED_BOTH)
        {
            this.setExtendedState(Program_1.MAXIMIZED_BOTH);
        }
        else
        {
            this.setExtendedState(Program_1.NORMAL);
        }
    }//GEN-LAST:event_MaxIconMouseClicked

    private void MaxIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxIconMouseEntered
        changecolor(BTNMax, new Color(200,200,200));
    }//GEN-LAST:event_MaxIconMouseEntered

    private void MaxIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxIconMouseExited
        changecolor(BTNMax, new Color(255,255,255));
    }//GEN-LAST:event_MaxIconMouseExited

    private void ExitIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitIconMouseEntered
        changecolor(BTNClose, new Color(200,200,200));
    }//GEN-LAST:event_ExitIconMouseEntered

    private void ExitIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitIconMouseExited
        changecolor(BTNClose, new Color(255,255,255));

    }//GEN-LAST:event_ExitIconMouseExited

    private void Dashboard_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dashboard_BTNActionPerformed
        Dashboard_BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Dashboard Dashboard = new Dashboard();
            Dashboard.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Dashboard_BTNActionPerformed

    private void Dashboard_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard_BTNMouseEntered
        Dashboard_BTN.setForeground(Color.BLACK);
        Dashboard_BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_Dashboard_BTNMouseEntered

    private void Dashboard_BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dashboard_BTNMouseExited
        Dashboard_BTN.setForeground(Color.WHITE);
        Dashboard_BTN.setBackground(new Color(118,16,198));
    }//GEN-LAST:event_Dashboard_BTNMouseExited

    private void Dev_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dev_BTNMouseEntered
        Dev_BTN.setForeground(Color.WHITE);
        Dev_BTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_Dev_BTNMouseEntered

    private void Dev_BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Dev_BTNMouseExited
        Dev_BTN.setForeground(Color.BLACK);
        Dev_BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_Dev_BTNMouseExited

    private void Dev_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dev_BTNActionPerformed
        Dev_BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            About_Dev About_Dev = new About_Dev();
            About_Dev.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Dev_BTNActionPerformed

    private void App_BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_App_BTNMouseEntered
       App_BTN.setForeground(Color.WHITE);
       App_BTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_App_BTNMouseEntered

    private void App_BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_App_BTNMouseExited
        App_BTN.setForeground(Color.BLACK);
        App_BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_App_BTNMouseExited

    private void App_BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_App_BTNActionPerformed
        App_BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            About_App AboutApp = new About_App();
            AboutApp.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_App_BTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (Exception ex) {
        java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }

    java.awt.EventQueue.invokeLater(() -> {
        new Main().setVisible(true);
    });
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton App_BTN;
    private javax.swing.JPanel BTNClose;
    private javax.swing.JPanel BTNMax;
    private javax.swing.JPanel BTNMin;
    private javax.swing.JButton Dashboard_BTN;
    private javax.swing.JButton Dev_BTN;
    private javax.swing.JLabel ExitIcon;
    private javax.swing.JPanel Header;
    private javax.swing.JPanel IconMinMax;
    private javax.swing.JPanel MainBoard;
    private javax.swing.JLabel MaxIcon;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
