/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

import javax.swing.*;
import java.awt.*;
import java.awt.event.*;

public class Program_1_Start extends javax.swing.JFrame {

    /**
     * Creates new form Program_1
     */
    
    public Program_1_Start() {
        initComponents();
        this.setUndecorated(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // This class defines the gradient panel
class jPanelGradient extends JPanel {
    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Always call super.paintComponent(g)
        
        Graphics2D g2d = (Graphics2D) g;
        int width = getWidth();
        int height = getHeight();
        
        // Define lighter pastel colors by mixing original colors with white
        Color color1 = new Color(255, 210, 220); // Lighter Pink (mix of pink and white)
        Color color2 = new Color(230, 210, 230); // Lighter Purple (mix of purple and white)
        Color color3 = new Color(200, 230, 255); // Lighter Blue (mix of blue and white)
        
        // Create a gradient paint with three lighter colors
        GradientPaint gradient = new GradientPaint(0, 0, color1, width, height, color3);
        
        // Set the graphics object to use the gradient
        g2d.setPaint(gradient);
        
        // Fill the entire panel with the gradient
        g2d.fillRect(0, 0, width, height);
    }
}

// This class defines the transparent panel
class jPanelTransparent extends JPanel {
    public jPanelTransparent() {
        // Set panel to be transparent for background
        setOpaque(false);
    }

    protected void paintComponent(Graphics g) {
        super.paintComponent(g); // Always call super.paintComponent(g)
        
        Graphics2D g2d = (Graphics2D) g;
        int width = getWidth();
        int height = getHeight();
        
        // Set the color to white with some transparency (alpha = 128 for 50% transparency)
        Color semiTransparentWhite = new Color(255, 255, 255, 128); // White with 50% opacity

        // Fill the entire panel with a semi-transparent white background
        g2d.setColor(semiTransparentWhite);
        g2d.fillRect(0, 0, width, height); // Fill the entire panel area
    }
}

private void resetButtonColors() {
    // Reset all buttons to their default color
    Program_1BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_2BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_3BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_4BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_5BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_6BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_7BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_8BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_9BTN.setBackground(new java.awt.Color(250, 250, 245));
    Program_10BTN.setBackground(new java.awt.Color(250, 250, 245));
    // Add more buttons if necessary
}

   
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        IconMinMax = new javax.swing.JPanel();
        BTNMax = new javax.swing.JPanel();
        MaxIcon = new javax.swing.JLabel();
        BTNClose = new javax.swing.JPanel();
        ExitIcon = new javax.swing.JLabel();
        BTNMin = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        MainBoard = new jPanelGradient();
        MenuIcon = new javax.swing.JPanel();
        linehidemenu = new javax.swing.JPanel();
        HomeIcon = new javax.swing.JLabel();
        hideMenu = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        ExitBTN = new javax.swing.JButton();
        Program_2BTN = new javax.swing.JButton();
        Program_3BTN = new javax.swing.JButton();
        Program_4BTN = new javax.swing.JButton();
        Program_5BTN = new javax.swing.JButton();
        Program_6BTN = new javax.swing.JButton();
        Program_7BTN = new javax.swing.JButton();
        Program_8BTN = new javax.swing.JButton();
        Program_9BTN = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        Program_10BTN = new javax.swing.JButton();
        DashboardBTN = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        Program_1BTN = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new jPanelTransparent();
        jLabel20 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        input2 = new javax.swing.JTextField();
        input4 = new javax.swing.JTextField();
        input3 = new javax.swing.JTextField();
        input5 = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        input1 = new javax.swing.JTextArea();
        SubmitBTN = new javax.swing.JButton();
        jPanel5 = new jPanelTransparent();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        output2 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        output3 = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        output4 = new javax.swing.JTextField();
        output1 = new javax.swing.JTextField();
        ClearBTN1 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.BorderLayout());

        Header.setBackground(new java.awt.Color(255, 255, 255));
        Header.setPreferredSize(new java.awt.Dimension(800, 35));
        Header.setLayout(new java.awt.BorderLayout());

        IconMinMax.setBackground(new java.awt.Color(0, 0, 51));
        IconMinMax.setPreferredSize(new java.awt.Dimension(150, 50));
        IconMinMax.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BTNMax.setBackground(new java.awt.Color(255, 255, 255));

        MaxIcon.setBackground(new java.awt.Color(255, 255, 255));
        MaxIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MaxIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/2.png"))); // NOI18N
        MaxIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MaxIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MaxIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MaxIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BTNMaxLayout = new javax.swing.GroupLayout(BTNMax);
        BTNMax.setLayout(BTNMaxLayout);
        BTNMaxLayout.setHorizontalGroup(
            BTNMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MaxIcon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        BTNMaxLayout.setVerticalGroup(
            BTNMaxLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNMaxLayout.createSequentialGroup()
                .addComponent(MaxIcon)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        IconMinMax.add(BTNMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 0, 50, -1));

        BTNClose.setBackground(new java.awt.Color(255, 255, 255));

        ExitIcon.setBackground(new java.awt.Color(255, 255, 255));
        ExitIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/1.png"))); // NOI18N
        ExitIcon.setToolTipText("");
        ExitIcon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitIconMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitIconMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitIconMouseExited(evt);
            }
        });

        javax.swing.GroupLayout BTNCloseLayout = new javax.swing.GroupLayout(BTNClose);
        BTNClose.setLayout(BTNCloseLayout);
        BTNCloseLayout.setHorizontalGroup(
            BTNCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ExitIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
        );
        BTNCloseLayout.setVerticalGroup(
            BTNCloseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BTNCloseLayout.createSequentialGroup()
                .addComponent(ExitIcon)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        IconMinMax.add(BTNClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 0, 50, -1));

        BTNMin.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout BTNMinLayout = new javax.swing.GroupLayout(BTNMin);
        BTNMin.setLayout(BTNMinLayout);
        BTNMinLayout.setHorizontalGroup(
            BTNMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );
        BTNMinLayout.setVerticalGroup(
            BTNMinLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 52, Short.MAX_VALUE)
        );

        IconMinMax.add(BTNMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, -1));

        Header.add(IconMinMax, java.awt.BorderLayout.LINE_END);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 62, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );

        Header.add(jPanel1, java.awt.BorderLayout.LINE_START);

        jLabel1.setBackground(new java.awt.Color(118, 16, 198));
        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Header.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(Header, java.awt.BorderLayout.PAGE_START);

        MainBoard.setBackground(new java.awt.Color(255, 246, 255));

        MenuIcon.setBackground(new java.awt.Color(255, 255, 255));
        MenuIcon.setPreferredSize(new java.awt.Dimension(50, 450));
        MenuIcon.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        linehidemenu.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout linehidemenuLayout = new javax.swing.GroupLayout(linehidemenu);
        linehidemenu.setLayout(linehidemenuLayout);
        linehidemenuLayout.setHorizontalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        linehidemenuLayout.setVerticalGroup(
            linehidemenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        MenuIcon.add(linehidemenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 50, 10));

        HomeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/5.png"))); // NOI18N
        MenuIcon.add(HomeIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, -1));

        hideMenu.setBackground(new java.awt.Color(255, 255, 255));
        hideMenu.setLayout(new java.awt.BorderLayout());
        MenuIcon.add(hideMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 50, 40));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("GENERAL");
        MenuIcon.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, -1));

        ExitBTN.setBackground(new java.awt.Color(250, 250, 245));
        ExitBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        ExitBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/16.png"))); // NOI18N
        ExitBTN.setText("Exit                     ");
        ExitBTN.setToolTipText("");
        ExitBTN.setBorder(null);
        ExitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitBTNMouseExited(evt);
            }
        });
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });
        MenuIcon.add(ExitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 590, 150, 40));

        Program_2BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_2BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_2BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/7.png"))); // NOI18N
        Program_2BTN.setText("Barkada Outing     ");
        Program_2BTN.setToolTipText("");
        Program_2BTN.setBorder(null);
        Program_2BTN.setBorderPainted(false);
        Program_2BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_2BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_2BTNMouseExited(evt);
            }
        });
        Program_2BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_2BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_2BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 150, -1));

        Program_3BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_3BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_3BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/8.png"))); // NOI18N
        Program_3BTN.setText(" Vaccine Tracker     ");
        Program_3BTN.setToolTipText("");
        Program_3BTN.setBorder(null);
        Program_3BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_3BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_3BTNMouseExited(evt);
            }
        });
        Program_3BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_3BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_3BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));

        Program_4BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_4BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_4BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/9.png"))); // NOI18N
        Program_4BTN.setText("Kuryente Bill Mo!   ");
        Program_4BTN.setToolTipText("");
        Program_4BTN.setBorder(null);
        Program_4BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_4BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_4BTNMouseExited(evt);
            }
        });
        Program_4BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_4BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_4BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, -1));

        Program_5BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_5BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_5BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/10.png"))); // NOI18N
        Program_5BTN.setText(" Jeepney Driver     ");
        Program_5BTN.setToolTipText("");
        Program_5BTN.setBorder(null);
        Program_5BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_5BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_5BTNMouseExited(evt);
            }
        });
        Program_5BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_5BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_5BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, -1));

        Program_6BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_6BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_6BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/11.png"))); // NOI18N
        Program_6BTN.setText("Sinehan Earnings  ");
        Program_6BTN.setToolTipText("");
        Program_6BTN.setBorder(null);
        Program_6BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_6BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_6BTNMouseExited(evt);
            }
        });
        Program_6BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_6BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_6BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, -1));

        Program_7BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_7BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_7BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/12.png"))); // NOI18N
        Program_7BTN.setText("Palengke Budget  ");
        Program_7BTN.setToolTipText("");
        Program_7BTN.setBorder(null);
        Program_7BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_7BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_7BTNMouseExited(evt);
            }
        });
        Program_7BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_7BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_7BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, -1));

        Program_8BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_8BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_8BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/13.png"))); // NOI18N
        Program_8BTN.setText(" Laundry Pricing      ");
        Program_8BTN.setToolTipText("");
        Program_8BTN.setBorder(null);
        Program_8BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_8BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_8BTNMouseExited(evt);
            }
        });
        Program_8BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_8BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_8BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, -1));

        Program_9BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_9BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_9BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/14.png"))); // NOI18N
        Program_9BTN.setText("Typhoon Alert Level");
        Program_9BTN.setToolTipText("");
        Program_9BTN.setBorder(null);
        Program_9BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_9BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_9BTNMouseExited(evt);
            }
        });
        Program_9BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_9BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_9BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("PROGRAMS");
        MenuIcon.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        Program_10BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_10BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_10BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/15.png"))); // NOI18N
        Program_10BTN.setText("Shipping Fee         ");
        Program_10BTN.setToolTipText("");
        Program_10BTN.setBorder(null);
        Program_10BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_10BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_10BTNMouseExited(evt);
            }
        });
        Program_10BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_10BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_10BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, 150, 40));

        DashboardBTN.setBackground(new java.awt.Color(250, 250, 245));
        DashboardBTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        DashboardBTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/17.png"))); // NOI18N
        DashboardBTN.setText("Dashboard            ");
        DashboardBTN.setToolTipText("");
        DashboardBTN.setBorder(null);
        DashboardBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DashboardBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DashboardBTNMouseExited(evt);
            }
        });
        DashboardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DashboardBTNActionPerformed(evt);
            }
        });
        MenuIcon.add(DashboardBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 550, 150, 40));

        jLabel6.setBackground(new java.awt.Color(0, 0, 0));
        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("BayanApp");
        MenuIcon.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 120, -1));

        Program_1BTN.setBackground(new java.awt.Color(250, 250, 245));
        Program_1BTN.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        Program_1BTN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/6.png"))); // NOI18N
        Program_1BTN.setText("Mutya ng Barangay");
        Program_1BTN.setToolTipText("");
        Program_1BTN.setBorder(null);
        Program_1BTN.setBorderPainted(false);
        Program_1BTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Program_1BTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Program_1BTNMouseExited(evt);
            }
        });
        Program_1BTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Program_1BTNActionPerformed(evt);
            }
        });
        MenuIcon.add(Program_1BTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 150, -1));

        jLabel5.setBackground(new java.awt.Color(0, 0, 0));
        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Pageant");

        jPanel2.setPreferredSize(new java.awt.Dimension(300, 400));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Contestant Name:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Judge Scores and Text Votes");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Judge 1:");

        jLabel17.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel17.setText("Judge 2:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Text Votes:");

        jLabel23.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel23.setText("Judge 3:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(118, 16, 198));
        jLabel13.setText("INPUT");

        input2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        input4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        input3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        input5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        input1.setColumns(20);
        input1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        input1.setRows(5);
        jScrollPane2.setViewportView(input1);

        SubmitBTN.setBackground(new java.awt.Color(118, 16, 198));
        SubmitBTN.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        SubmitBTN.setForeground(new java.awt.Color(255, 255, 255));
        SubmitBTN.setText("Submit");
        SubmitBTN.setToolTipText("");
        SubmitBTN.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        SubmitBTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                SubmitBTNMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                SubmitBTNMouseExited(evt);
            }
        });
        SubmitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBTNActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(18, 18, 18)
                                .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(18, 18, 18)
                                .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(179, 179, 179)
                        .addComponent(SubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel13)
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(jLabel20))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel12)
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(input2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel23)
                    .addComponent(input4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(input3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(input5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SubmitBTN, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jPanel5.setPreferredSize(new java.awt.Dimension(300, 400));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(118, 16, 198));
        jLabel26.setText("RESULT");

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Judge Average Score: ");

        output2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        output2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                output2ActionPerformed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Text Vote Points");

        output3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Contestant Name:");

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel30.setText("Final Score:");

        output4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        output4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                output4ActionPerformed(evt);
            }
        });

        output1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        ClearBTN1.setBackground(new java.awt.Color(118, 16, 198));
        ClearBTN1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ClearBTN1.setForeground(new java.awt.Color(255, 255, 255));
        ClearBTN1.setText("Clear");
        ClearBTN1.setToolTipText("");
        ClearBTN1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        ClearBTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClearBTN1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClearBTN1MouseExited(evt);
            }
        });
        ClearBTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearBTN1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel27)
                    .addComponent(jLabel28)
                    .addComponent(jLabel29)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(output4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(output1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(output2, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                        .addComponent(output3)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(ClearBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(205, 205, 205))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel26)
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel29)
                    .addComponent(output1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(output2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel28)
                    .addComponent(output3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(output4, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addComponent(ClearBTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jLabel7.setBackground(new java.awt.Color(0, 0, 0));
        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(118, 16, 198));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Scoring System");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Mutya ng Barangray");

        javax.swing.GroupLayout MainBoardLayout = new javax.swing.GroupLayout(MainBoard);
        MainBoard.setLayout(MainBoardLayout);
        MainBoardLayout.setHorizontalGroup(
            MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainBoardLayout.createSequentialGroup()
                .addComponent(MenuIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(MainBoardLayout.createSequentialGroup()
                        .addGap(55, 55, 55)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55))
                    .addGroup(MainBoardLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBoardLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(MainBoardLayout.createSequentialGroup()
                                .addGap(158, 158, 158)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(295, 295, 295))))
        );
        MainBoardLayout.setVerticalGroup(
            MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuIcon, javax.swing.GroupLayout.DEFAULT_SIZE, 745, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainBoardLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addGap(15, 15, 15)
                .addComponent(jLabel4)
                .addGap(56, 56, 56)
                .addGroup(MainBoardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(MainBoard, java.awt.BorderLayout.CENTER);

        setSize(new java.awt.Dimension(1416, 788));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void changecolor(JPanel hover, Color rand)
    {
        hover.setBackground(rand);
    }
    
    public void clickMenu(JPanel h1, int numberbool)
    {
        if (numberbool == 1)
        {
            h1.setBackground(new Color(255,255,204));
            //h2.setBackground(new Color(5,10,46));
        }
        else
        {
            h1.setBackground(new Color(200,200,200));
            //h2.setBackground(new Color(25,29,74));
        }
    }
    
    public void hideShow(JPanel menushowhide, boolean dashboard) {
        if (dashboard) {
            menushowhide.setPreferredSize(new Dimension(50, menushowhide.getHeight()));
        } else {
            menushowhide.setPreferredSize(new Dimension(270, menushowhide.getHeight()));
        }
    }


    
    private void ExitIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitIconMouseClicked
                   int confirm = JOptionPane.showConfirmDialog(
                this, 
                "Are you sure you want to exit BayanApp?", 
                "Exit Confirmation", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if (confirm == JOptionPane.YES_OPTION) {
                Bye byePage = new Bye();
                byePage.setVisible(true);

                this.setVisible(false);

                new javax.swing.Timer(2000, (e) -> {
                    System.exit(0);
                }).start();
            }
    }//GEN-LAST:event_ExitIconMouseClicked

    private void MaxIconMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxIconMouseClicked
        if(this.getExtendedState()!= Program_1.MAXIMIZED_BOTH)
        {
            this.setExtendedState(Program_1.MAXIMIZED_BOTH);
        }
        else
        {
            this.setExtendedState(Program_1.NORMAL);
        }
    }//GEN-LAST:event_MaxIconMouseClicked

    private void MaxIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxIconMouseEntered
        changecolor(BTNMax, new Color(200,200,200));
    }//GEN-LAST:event_MaxIconMouseEntered

    private void MaxIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MaxIconMouseExited
        changecolor(BTNMax, new Color(255,255,255));
    }//GEN-LAST:event_MaxIconMouseExited

    private void ExitIconMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitIconMouseEntered
        changecolor(BTNClose, new Color(200,200,200));
    }//GEN-LAST:event_ExitIconMouseEntered

    private void ExitIconMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitIconMouseExited
        changecolor(BTNClose, new Color(255,255,255));

    }//GEN-LAST:event_ExitIconMouseExited

    private void ExitBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseEntered
        ExitBTN.setForeground(Color.WHITE);
        ExitBTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_ExitBTNMouseEntered

    private void ExitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBTNMouseExited
        ExitBTN.setForeground(Color.BLACK);
        ExitBTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_ExitBTNMouseExited

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
                    int confirm = JOptionPane.showConfirmDialog(
                this, 
                "Are you sure you want to exit BayanApp?", 
                "Exit Confirmation", 
                JOptionPane.YES_NO_OPTION,
                JOptionPane.QUESTION_MESSAGE
            );

            if (confirm == JOptionPane.YES_OPTION) {
                Bye byePage = new Bye();
                byePage.setVisible(true);

                this.setVisible(false);

                new javax.swing.Timer(2000, (e) -> {
                    System.exit(0);
                }).start();
            }
    }//GEN-LAST:event_ExitBTNActionPerformed

    private void Program_2BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_2BTNMouseEntered
        Program_2BTN.setForeground(Color.WHITE);
        Program_2BTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_Program_2BTNMouseEntered

    private void Program_2BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_2BTNMouseExited
        Program_2BTN.setForeground(Color.BLACK);
        Program_2BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_Program_2BTNMouseExited

    private void Program_2BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_2BTNActionPerformed
        Program_2BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_2 program2 = new Program_2();
            program2.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start(); 
    }//GEN-LAST:event_Program_2BTNActionPerformed

    private void Program_3BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_3BTNMouseEntered
        Program_3BTN.setForeground(Color.WHITE);
        Program_3BTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_Program_3BTNMouseEntered

    private void Program_3BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_3BTNMouseExited
        Program_3BTN.setForeground(Color.BLACK);
        Program_3BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_Program_3BTNMouseExited

    private void Program_3BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_3BTNActionPerformed
        Program_3BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_3 program3 = new Program_3();
            program3.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Program_3BTNActionPerformed

    private void Program_4BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_4BTNMouseEntered
        Program_4BTN.setForeground(Color.WHITE);
        Program_4BTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_Program_4BTNMouseEntered

    private void Program_4BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_4BTNMouseExited
        Program_4BTN.setForeground(Color.BLACK);
        Program_4BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_Program_4BTNMouseExited

    private void Program_4BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_4BTNActionPerformed
        Program_4BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_4 program4 = new Program_4();
            program4.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Program_4BTNActionPerformed

    private void Program_5BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_5BTNMouseEntered
        Program_5BTN.setForeground(Color.WHITE);
        Program_5BTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_Program_5BTNMouseEntered

    private void Program_5BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_5BTNMouseExited
        Program_5BTN.setForeground(Color.BLACK);
        Program_5BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_Program_5BTNMouseExited

    private void Program_5BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_5BTNActionPerformed
        Program_5BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_5 program5 = new Program_5();
            program5.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Program_5BTNActionPerformed

    private void Program_6BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_6BTNMouseEntered
        Program_6BTN.setForeground(Color.WHITE);
        Program_6BTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_Program_6BTNMouseEntered

    private void Program_6BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_6BTNMouseExited
        Program_6BTN.setForeground(Color.BLACK);
        Program_6BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_Program_6BTNMouseExited

    private void Program_6BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_6BTNActionPerformed
        Program_6BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_6 program6 = new Program_6();
            program6.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Program_6BTNActionPerformed

    private void Program_7BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_7BTNMouseEntered
        Program_7BTN.setForeground(Color.WHITE);
        Program_7BTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_Program_7BTNMouseEntered

    private void Program_7BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_7BTNMouseExited
        Program_7BTN.setForeground(Color.BLACK);
        Program_7BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_Program_7BTNMouseExited

    private void Program_7BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_7BTNActionPerformed
        Program_7BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_7 program7 = new Program_7();
            program7.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Program_7BTNActionPerformed

    private void Program_8BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_8BTNMouseEntered
        Program_8BTN.setForeground(Color.WHITE);
        Program_8BTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_Program_8BTNMouseEntered

    private void Program_8BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_8BTNMouseExited
        Program_8BTN.setForeground(Color.BLACK);
        Program_8BTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_Program_8BTNMouseExited

    private void Program_8BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_8BTNActionPerformed
        Program_8BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_8 program8 = new Program_8();
            program8.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Program_8BTNActionPerformed

    private void Program_9BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_9BTNMouseEntered
        Program_9BTN.setBackground(new Color(150, 50, 230));
        Program_9BTN.setForeground(Color.WHITE);
    }//GEN-LAST:event_Program_9BTNMouseEntered

    private void Program_9BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_9BTNMouseExited
        Program_9BTN.setBackground(Color.WHITE);
        Program_9BTN.setForeground(Color.BLACK);
    }//GEN-LAST:event_Program_9BTNMouseExited

    private void Program_9BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_9BTNActionPerformed
        Program_9BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_9 program9 = new Program_9();
            program9.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Program_9BTNActionPerformed

    private void Program_10BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_10BTNMouseEntered
        Program_10BTN.setBackground(new Color(150, 50, 230));
        Program_10BTN.setForeground(Color.WHITE);
    }//GEN-LAST:event_Program_10BTNMouseEntered

    private void Program_10BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_10BTNMouseExited
        Program_10BTN.setBackground(Color.WHITE);
        Program_10BTN.setForeground(Color.BLACK);
    }//GEN-LAST:event_Program_10BTNMouseExited

    private void Program_10BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_10BTNActionPerformed
        Program_10BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_10 program10 = new Program_10();
            program10.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Program_10BTNActionPerformed

    private void DashboardBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardBTNMouseEntered
        DashboardBTN.setForeground(Color.WHITE);
        DashboardBTN.setBackground(new Color(150, 50, 230));
    }//GEN-LAST:event_DashboardBTNMouseEntered

    private void DashboardBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DashboardBTNMouseExited
        DashboardBTN.setForeground(Color.BLACK);
        DashboardBTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_DashboardBTNMouseExited

    private void DashboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardBTNActionPerformed
        DashboardBTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Dashboard dashboard = new Dashboard();
            dashboard.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_DashboardBTNActionPerformed

    private void Program_1BTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_1BTNMouseEntered
        Program_1BTN.setBackground(new Color(150, 50, 230));
        Program_1BTN.setForeground(Color.WHITE);
        Program_1BTN.setBorderPainted(false);
        Program_1BTN.setBorder(null);
        Program_1BTN.setBorder(BorderFactory.createEmptyBorder());
    }//GEN-LAST:event_Program_1BTNMouseEntered

    private void Program_1BTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Program_1BTNMouseExited
        Program_1BTN.setBackground(Color.WHITE);
        Program_1BTN.setForeground(Color.BLACK);
    }//GEN-LAST:event_Program_1BTNMouseExited

    private void Program_1BTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Program_1BTNActionPerformed
        Program_1BTN.setEnabled(false);
        this.setVisible(false);

        Loading_Screen loading = new Loading_Screen();
        loading.setVisible(true);

        javax.swing.Timer timer = new javax.swing.Timer(2000, (e) -> {
            loading.dispose();
            Program_1 program1 = new Program_1();
            program1.setVisible(true);
            this.dispose();
        });
        timer.setRepeats(false);
        timer.start();
    }//GEN-LAST:event_Program_1BTNActionPerformed

    private void output2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_output2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_output2ActionPerformed

    private void SubmitBTNMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBTNMouseEntered
        SubmitBTN.setForeground(Color.BLACK);
        SubmitBTN.setBackground(Color.WHITE);
    }//GEN-LAST:event_SubmitBTNMouseEntered

    private void SubmitBTNMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_SubmitBTNMouseExited
        SubmitBTN.setForeground(Color.WHITE);
        SubmitBTN.setBackground(new Color(118,16,198));
    }//GEN-LAST:event_SubmitBTNMouseExited

    private void SubmitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBTNActionPerformed
    try {
        // Input
        String name = input1.getText();
        double score1 = Double.parseDouble(input2.getText());
        double score2 = Double.parseDouble(input3.getText());
        double score3 = Double.parseDouble(input4.getText());
        int votes = Integer.parseInt(input5.getText());

        // Processing
        double average = (score1 + score2 + score3) / 3;
        double votePoints = votes / 100.0;
        double result = (average * 0.5) + (votePoints * 0.5);

        // Output
        output1.setText(name);
        output2.setText(String.format("%.2f", average));
        output3.setText(String.format("%.2f", votePoints));
        output4.setText(String.format("%.2f", result));

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "Invalid input: Please enter valid numbers.", "Input Error", JOptionPane.ERROR_MESSAGE);
    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "An unexpected error occurred: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }

    }//GEN-LAST:event_SubmitBTNActionPerformed
 
    private void ClearBTN1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBTN1MouseEntered
        // TODO add your handling code here:
        ClearBTN1.setForeground(Color.BLACK);
        ClearBTN1.setBackground(Color.WHITE);
    }//GEN-LAST:event_ClearBTN1MouseEntered

    private void ClearBTN1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearBTN1MouseExited
        // TODO add your handling code here:
        ClearBTN1.setForeground(Color.WHITE);
        ClearBTN1.setBackground(new Color(118,16,198));
    }//GEN-LAST:event_ClearBTN1MouseExited

    private void ClearBTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearBTN1ActionPerformed
        // TODO add your handling code here:
        // Clear input fields
        input1.setText("");
        input2.setText("");
        input3.setText("");
        input4.setText("");
        input5.setText("");

        // Clear output fields
        output1.setText("");
        output2.setText("");
        output3.setText("");
        output4.setText("");
    }//GEN-LAST:event_ClearBTN1ActionPerformed

    private void output4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_output4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_output4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Program_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Program_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Program_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Program_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Program_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BTNClose;
    private javax.swing.JPanel BTNMax;
    private javax.swing.JPanel BTNMin;
    private javax.swing.JButton ClearBTN1;
    private javax.swing.JButton DashboardBTN;
    private javax.swing.JButton ExitBTN;
    private javax.swing.JLabel ExitIcon;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel HomeIcon;
    private javax.swing.JPanel IconMinMax;
    private javax.swing.JPanel MainBoard;
    private javax.swing.JLabel MaxIcon;
    private javax.swing.JPanel MenuIcon;
    private javax.swing.JButton Program_10BTN;
    private javax.swing.JButton Program_1BTN;
    private javax.swing.JButton Program_2BTN;
    private javax.swing.JButton Program_3BTN;
    private javax.swing.JButton Program_4BTN;
    private javax.swing.JButton Program_5BTN;
    private javax.swing.JButton Program_6BTN;
    private javax.swing.JButton Program_7BTN;
    private javax.swing.JButton Program_8BTN;
    private javax.swing.JButton Program_9BTN;
    private javax.swing.JButton SubmitBTN;
    private javax.swing.JPanel hideMenu;
    private javax.swing.JTextArea input1;
    private javax.swing.JTextField input2;
    private javax.swing.JTextField input3;
    private javax.swing.JTextField input4;
    private javax.swing.JTextField input5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel linehidemenu;
    private javax.swing.JTextField output1;
    private javax.swing.JTextField output2;
    private javax.swing.JTextField output3;
    private javax.swing.JTextField output4;
    // End of variables declaration//GEN-END:variables
}
